Repository ucsb-cs156-f24/proj-courses-f24-01, pull requests merged in 2024-11, with the labels that each got.

#14 Fixed annotation warning in pom.xml
  pom.xml
Labels: 5, Ready-For-Staff

#19 Added admin updates placeholder
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Admin/AdminUpdatesPage.js
  frontend/src/stories/pages/Admin/AdminUpdatesPage.stories.js
  frontend/src/tests/pages/AdminUpdatesPage.test.js
Labels: 5

#20 Add Purge Job Log Button to Admin Jobs Page
  frontend/src/main/pages/Admin/AdminJobsPage.js
  frontend/src/tests/pages/AdminJobsPage.test.js
Labels: 10

#22 Added stryker test to check disableGroupBy is true for all columns
  frontend/src/main/components/Sections/SectionsInstructorTable.js
  frontend/src/tests/components/Sections/SectionsInstructorTable.test.js
Labels: 10, Merge Candidate-CI

#23 Junhyung getactivequarterlist component
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBAPIQuarterController.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBAPIQuarterService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBAPIQuarterControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBAPIQuarterServiceTests.java
Labels: Ready-For-Staff

#21 COURSES-1: Duplicate personalschedules edit bug fixed
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesEditPage.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesEditPage.test.js
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesControllerTests.java
Labels: 10

#28 Fix backend error message bug when adding a different section from an existing course in personal schedule.
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
Labels: 10

#27 Descriptional Optional
  frontend/src/main/components/PersonalSchedules/PersonalScheduleForm.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesEditPage.js
  frontend/src/tests/components/PersonalSchedules/PersonalScheduleForm.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesCreatePage.test.js
  src/main/java/edu/ucsb/cs156/courses/entities/PersonalSchedule.java
Labels: Ready-For-Staff

#34 Added update table component
  frontend/src/fixtures/updateFixtures.js
  frontend/src/main/components/Updates/UpdateTable.js
  frontend/src/stories/components/Updates/UpdateTable.stories.js
  frontend/src/tests/components/Updates/UpdateTable.test.js
Labels: 10, Merge Candidate-CI, Ready-For-Staff

#25 deleted lines that caused clutter in my logs
  src/main/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataJob.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataJobTests.java
Labels: 5, Ready-For-Staff

#32 Cameron add finals info service v2
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumController.java
  src/main/java/edu/ucsb/cs156/courses/models/FinalExam.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: Ready-For-Staff
